services:
  - type: web
    name: 287-maktab-backend
    runtime: node
    repo: https://github.com/zuhriddinmusirmonov72-svg/287-maktab
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        value: 287maktab-super-secret-key-change-in-production-12345
    plan: free

